name: Allure Report

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  allure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean old Allure results
        run: rm -rf allure-results allure-history

      - name: Copy Results from repo
        run: |
          mkdir -p allure-results
          if [ -d "allure-results" ]; then
            cp -R allure-results/. allure-results/
          else
            echo "Results not found"
          fi

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 1

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          force_orphan: true