name: Allure Report

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  allure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'microsoft'

      # Запускаем все тесты проекта (UI и API)
      - name: Run All Tests
        run: mvn clean test
        continue-on-error: true

      - name: Copy Results to root
        run: |
          mkdir -p allure-results
          cp -R target/allure-results/. allure-results/ || echo "No results found"

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 5 # Храним только последние 5 запусков для динамики, остальное чистим

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          force_orphan: true